### ISSUE TITLE
Unable to create vehicle 

### ISSUE THREAD

**Issue by MartinStyk** [piskula/FuelUp#69]
Following exception is thrown

07-27 14:43:59.357 5522-5522/sk.piskula.fuelup E/VehicleService: Unexpected error. See logs for details.
                                                                 java.sql.SQLException: Unable to run insert stmt on object Vehicle{id=null, name=Kkk, type=VehicleType{id=1, name=Sedan}, volumeUnit=LITRE, vehicleMaker=null, startMileage=null, currency=EUR, pathToPicture=null}: INSERT INTO `vehicles` (`currency` ,`name` ,`path_to_picture` ,`start_mileage` ,`type_id` ,`vehicle_maker` ,`volume_unit` ) VALUES (?,?,?,?,?,?,?)
                                                                     at com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
                                                                     at com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:124)
                                                                     at com.j256.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:394)
                                                                     at com.j256.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:308)
                                                                     at sk.piskula.fuelup.business.VehicleService.save(VehicleService.java:57)
                                                                     at sk.piskula.fuelup.business.VehicleService.save(VehicleService.java:46)
                                                                     at sk.piskula.fuelup.screens.VehicleListFragment.onDialogCreateBtnClick(VehicleListFragment.java:114)
                                                                     at sk.piskula.fuelup.screens.MainActivity.onDialogCreateBtnClick(MainActivity.java:87)
                                                                     at sk.piskula.fuelup.screens.dialog.CreateVehicleDialog$2.onClick(CreateVehicleDialog.java:47)
                                                                     at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:161)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                     at android.os.Looper.loop(Looper.java:153)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5299)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:511)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
                                                                     at dalvik.system.NativeStart.main(Native Method)
                                                                  Caused by: java.sql.SQLException: inserting to database failed: INSERT INTO `vehicles` (`currency` ,`name` ,`path_to_picture` ,`start_mileage` ,`type_id` ,`vehicle_maker` ,`volume_unit` ) VALUES (?,?,?,?,?,?,?)
                                                                     at com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
                                                                     at com.j256.ormlite.android.AndroidDatabaseConnection.insert(AndroidDatabaseConnection.java:159)
                                                                     at com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:89)
                                                                     at com.j256.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:394) 
                                                                     at com.j256.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:308) 
                                                                     at sk.piskula.fuelup.business.VehicleService.save(VehicleService.java:57) 
                                                                     at sk.piskula.fuelup.business.VehicleService.save(VehicleService.java:46) 
                                                                     at sk.piskula.fuelup.screens.VehicleListFragment.onDialogCreateBtnClick(VehicleListFragment.java:114) 
                                                                     at sk.piskula.fuelup.screens.MainActivity.onDialogCreateBtnClick(MainActivity.java:87) 
                                                                     at sk.piskula.fuelup.screens.dialog.CreateVehicleDialog$2.onClick(CreateVehicleDialog.java:47) 
                                                                     at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:161) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                     at android.os.Looper.loop(Looper.java:153) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5299) 
                                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600) 
                                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                                  Caused by: android.database.sqlite.SQLiteConstraintException: vehicles.distance_unit may not be NULL (code 19)
                                                                     at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
                                                                     at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:779)
                                                                     at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
                                                                     at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
                                                                     at com.j256.ormlite.android.AndroidDatabaseConnection.insert(AndroidDatabaseConnection.java:147)
                                                                     at com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:89) 
                                                                     at com.j256.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:394) 
                                                                     at com.j256.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:308) 
                                                                     at sk.piskula.fuelup.business.VehicleService.save(VehicleService.java:57) 
                                                                     at sk.piskula.fuelup.business.VehicleService.save(VehicleService.java:46) 
                                                                     at sk.piskula.fuelup.screens.VehicleListFragment.onDialogCreateBtnClick(VehicleListFragment.java:114) 
                                                                     at sk.piskula.fuelup.screens.MainActivity.onDialogCreateBtnClick(MainActivity.java:87) 
                                                                     at sk.piskula.fuelup.screens.dialog.CreateVehicleDialog$2.onClick(CreateVehicleDialog.java:47) 
                                                                     at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:161) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                     at android.os.Looper.loop(Looper.java:153) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5299) 
                                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600) 
                                                                     at dalvik.system.NativeStart.main(Native Method)

**Comment by MartinStyk** [comment]
This is caused by DB schema change
