### ISSUE TITLE
Deleting single fill up causes app crash

### ISSUE THREAD

**Issue by MartinStyk** [piskula/FuelUp#75]
There is only one fill up - delete it - booom !
java.lang.NullPointerException: Attempt to invoke virtual method 'double java.math.BigDecimal.doubleValue()' on a null object reference
                                                                       at sk.piskula.fuelup.data.provider.VehicleProvider.deleteFillUpInTransaction(VehicleProvider.java:932)
                                                                       at sk.piskula.fuelup.data.provider.VehicleProvider.delete(VehicleProvider.java:188)
                                                                       at android.content.ContentProvider$Transport.delete(ContentProvider.java:312)
                                                                       at android.content.ContentResolver.delete(ContentResolver.java:1299)
                                                                       at sk.piskula.fuelup.screens.edit.EditFillUpActivity.onDeleteDialogPositiveClick(EditFillUpActivity.java:263)
                                                                       at sk.piskula.fuelup.screens.dialog.DeleteDialog$2.onClick(DeleteDialog.java:56)
                                                                       at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:162)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:135)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by MartinStyk** [comment]
Already fixed
